#name: Ruby

#on: [push]

#jobs:
#  test:
#    strategy:
#      fail-fast: false
#      matrix:
#        ruby-version: ["3.0", "3.1", "3.2", "3.3", "3.4"]
#        os: [ubuntu-latest]

#    runs-on: ${{ matrix.os }}

#  NOTE: These tests have been broken since May 14, 2014 (https://github.com/aurorasolar/dxf-ruby/commit/54b332eefbbf4ba456ae267ea285d26f2e3c3bd0)

#    steps:
#      - uses: actions/checkout@v4
#      - uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: ${{ matrix.ruby-version }}
#          bundler-cache: true
#      - run: bundle exec rake
      